CREATE TABLE #VENTES (NoClient VARCHAR(50),
NomSousFamille VARCHAR(50),
ItemNo VARCHAR(50),
NomFamille VARCHAR(50),
DescProduit VARCHAR(50),
[Format] VARCHAR(50),
Marque VARCHAR(20),
Marche VARCHAR(20),
Poids INT ,Montant DECIMAL(10,4),
MontantBrute DECIMAL(10,4))